package com.jz.jzcore.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public voID configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("INTEGRAL_VIP", "ID", IntegralVip.class);//会员积分
		arp.addMapping("INTEGRAL_RULE", "ID", IntegralRule.class);//会员积分规则
		arp.addMapping("WX_CONFIG", "ID", WxConfig.class);//微信配置
		arp.addMapping("WX_USER", "ID", WxUser.class);//微信用户
		arp.addMapping("WINNING_DELIVERY", "ID", WinningDelivery.class);//奖品派送
		arp.addMapping("QRCODE_INFO", "ID",QRcodeInfo.class);//二维码
		arp.addMapping("SIGN_GOODS", "ID",SignGoods.class);//扫码发货
		arp.addMapping("PRODUCT_INFO", "ID",ProductInfo.class);//扫码发货
		arp.addMapping("ACTIVITY_REPORT", "ID",ActivityReport.class);//活动报备
		arp.addMapping("TURNTABLE_RAFFLE", "ID",TurntableRaffle.class);//活动报备奖品
		arp.addMapping("WX_CARD", "ID",WxCard.class);//微信卡券
		arp.addMapping("SYS_USER", "ID",SystemUser.class);//系统用户
		arp.addMapping("CANCEL_USER", "ID",CancelUser.class);//核销是否登陆表
		arp.addMapping("SYS_OFFICE", "ID",SystemOffice.class);//部门
		arp.addMapping("SYS_AREA", "ID",SystemArea.class);//地区
		arp.addMapping("LOCAL_CANCEL", "ID",LocalCancel.class);//本地核销
		arp.addMapping("REMOTE_CANCEL", "ID",RemoteCancel.class);//异地核销
		arp.addMapping("INTEGRAL_MALL", "ID",IntegralMall.class);//积分兑换
		arp.addMapping("PROVINCES_COUNT", "ID",ProvincesCount.class);//记录扫码区域与扫码次数
		arp.addMapping("ACCOUNTS", "ID",Accounts.class);//对账记录
		arp.addMapping("ACCOUNTSAPPLY", "ID",AccountsApply.class);//对账申请
		arp.addMapping("LOGISTICS_FIRM", "ID",LogisticeFirm.class);//快递公司
		arp.addMapping("ACTIVITYORDER", "ID",ActivityOrder.class);//活动运单中间表
		arp.addMapping("SALESMAN", "ID",SalesMan.class);//业务员
	}
}

